language: node_js

sudo: required

group: edge

node_js:
- '0.10'
- '0.11'

matrix:
  allow_failures:
  - node_js: '0.11'

after_script: dpkg --get-selections | grep -v deinstall | awk '{ print $1 }'
